server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: app:app@tcp(mysql:3306)/app
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  etcd:
    endpoints:
      - etcd:2379
